# Generated by Django 3.2.7 on 2021-11-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_postseg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antseg',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='postseg',
            name='photo',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('antseg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.antseg')),
                ('postseg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.postseg')),
            ],
        ),
    ]
