# Generated by Django 3.2.7 on 2021-11-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211123_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='antseg',
            name='choice',
            field=models.CharField(choices=[('A', 'Anterior'), ('P', 'Posterior')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postseg',
            name='choice',
            field=models.CharField(choices=[('A', 'Anterior'), ('P', 'Posterior')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
