# Generated by Django 3.2.7 on 2021-11-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211123_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antseg',
            old_name='choice',
            new_name='segment',
        ),
        migrations.RenameField(
            model_name='postseg',
            old_name='choice',
            new_name='segment',
        ),
    ]
